"""empty message

Revision ID: 0394435baacb
Revises: 6212bdbed1d4
Create Date: 2023-03-30 11:42:47.375781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0394435baacb'
down_revision = '6212bdbed1d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abnormal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abnormal', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
