"""empty message

Revision ID: 078db1489169
Revises: e336b6cfb672
Create Date: 2023-03-28 19:22:01.909849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '078db1489169'
down_revision = 'e336b6cfb672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enterprise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stockid', sa.String(length=50), nullable=True),
    sa.Column('stockname', sa.String(length=200), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('createtime', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('desc', sa.String(length=800), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enterprise')
    # ### end Alembic commands ###
