"""empty message

Revision ID: 22e165bc8e96
Revises: 0394435baacb
Create Date: 2023-03-30 11:43:12.282836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22e165bc8e96'
down_revision = '0394435baacb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abnormal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eid', sa.String(length=36), nullable=True),
    sa.Column('abnormal_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('abnormal')
    # ### end Alembic commands ###
