"""empty message

Revision ID: 47ad54a55e2e
Revises: a060ee8739e4
Create Date: 2023-04-06 21:47:58.568038

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '47ad54a55e2e'
down_revision = 'a060ee8739e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('new_job', schema=None) as batch_op:
        batch_op.alter_column('start_date',
               existing_type=mysql.DATETIME(),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('new_job', schema=None) as batch_op:
        batch_op.alter_column('start_date',
               existing_type=sa.String(length=100),
               type_=mysql.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
