"""empty message

Revision ID: 6212bdbed1d4
Revises: 078db1489169
Create Date: 2023-03-30 11:33:44.136410

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6212bdbed1d4'
down_revision = '078db1489169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abnormal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eid', sa.String(length=36), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('executedpersons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eid', sa.String(length=36), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eid', sa.String(length=36), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('serious_illegal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eid', sa.String(length=36), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enterprise', schema=None) as batch_op:
        batch_op.alter_column('eid',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.alter_column('longitude',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('latitude',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('gd_longitude',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('gd_latitude',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('row_update_time',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('regist_capi',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(asdecimal=True),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enterprise', schema=None) as batch_op:
        batch_op.alter_column('regist_capi',
               existing_type=sa.Float(asdecimal=True),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('row_update_time',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('gd_latitude',
               existing_type=sa.Float(asdecimal=True),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('gd_longitude',
               existing_type=sa.Float(asdecimal=True),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(asdecimal=True),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.Float(asdecimal=True),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('eid',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=True)

    op.drop_table('serious_illegal')
    op.drop_table('executions')
    op.drop_table('executedpersons')
    op.drop_table('abnormal')
    # ### end Alembic commands ###
