"""empty message

Revision ID: 9260df9e6559
Revises: ffb53afe9c24
Create Date: 2023-03-30 17:35:27.460939

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9260df9e6559'
down_revision = 'ffb53afe9c24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_enterprise')
    op.drop_table('t_rank')
    with op.batch_alter_table('enterprise_rank', schema=None) as batch_op:
        batch_op.alter_column('eid',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.alter_column('longitude',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('latitude',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('gd_longitude',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('gd_latitude',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('row_update_time',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('regist_capi',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('gongshangbx_num',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enterprise_rank', schema=None) as batch_op:
        batch_op.alter_column('gongshangbx_num',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
        batch_op.alter_column('regist_capi',
               existing_type=sa.Float(asdecimal=True),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('row_update_time',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('gd_latitude',
               existing_type=sa.Float(asdecimal=True),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('gd_longitude',
               existing_type=sa.Float(asdecimal=True),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(asdecimal=True),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.Float(asdecimal=True),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('eid',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=True)

    op.create_table('t_rank',
    sa.Column('eid', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('shiyebx_num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('yiliaobx_num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('gongshangbx_num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('dw_shiyebx_js', mysql.FLOAT(), nullable=True),
    sa.Column('score', mysql.FLOAT(), nullable=True),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('t_enterprise',
    sa.Column('eid', mysql.CHAR(length=36), nullable=True),
    sa.Column('reg_no', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('credit_no', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('org_no', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('format_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('category', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('province', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('econ_kind', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('scope', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('term_start', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('term_end', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('check_date', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('belong_org', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('oper_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('oper_type', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('oper_name_id', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('start_date', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('end_date', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('type_desc', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('longitude', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('latitude', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('gd_longitude', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('gd_latitude', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('obj_id', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('source', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('row_update_time', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('province_code', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('district_code', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('title_code', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('econ_kind_code', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('regist_capi_new', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('currency_unit', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('belong_org_code', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('credit_area_code', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('new_status_code', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('type_new', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('category_new', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('out_time', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('diaoxiao_time', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('regist_capi', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('created_time1', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('last_update_time1', mysql.VARCHAR(length=100), nullable=True),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
