"""empty message

Revision ID: b57ee3ac4146
Revises: 47ad54a55e2e
Create Date: 2023-04-07 08:48:58.172398

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b57ee3ac4146'
down_revision = '47ad54a55e2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('new_job', schema=None) as batch_op:
        batch_op.alter_column('start_date',
               existing_type=mysql.DATETIME(),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('new_job', schema=None) as batch_op:
        batch_op.alter_column('start_date',
               existing_type=sa.String(length=100),
               type_=mysql.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
