"""empty message

Revision ID: fd6db7be727e
Revises: c42d9577cad3
Create Date: 2023-03-30 17:02:05.724264

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fd6db7be727e'
down_revision = 'c42d9577cad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enterprise_rank', schema=None) as batch_op:
        batch_op.add_column(sa.Column('row_update_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('province_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('district_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('title_code', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('econ_kind_code', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('regist_capi_new', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('currency_unit', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('belong_org_code', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('credit_area_code', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('new_status_code', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('type_new', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('category_new', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('out_time', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('diaoxiao_time', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('regist_capi', sa.Float(asdecimal=True), nullable=True))
        batch_op.add_column(sa.Column('created_time', sa.String(length=100), nullable=True))
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enterprise_rank', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('created_time')
        batch_op.drop_column('regist_capi')
        batch_op.drop_column('diaoxiao_time')
        batch_op.drop_column('out_time')
        batch_op.drop_column('category_new')
        batch_op.drop_column('type_new')
        batch_op.drop_column('new_status_code')
        batch_op.drop_column('credit_area_code')
        batch_op.drop_column('belong_org_code')
        batch_op.drop_column('currency_unit')
        batch_op.drop_column('regist_capi_new')
        batch_op.drop_column('econ_kind_code')
        batch_op.drop_column('title_code')
        batch_op.drop_column('district_code')
        batch_op.drop_column('province_code')
        batch_op.drop_column('row_update_time')

    # ### end Alembic commands ###
