"""empty message

Revision ID: ffb53afe9c24
Revises: fd6db7be727e
Create Date: 2023-03-30 17:11:19.475569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffb53afe9c24'
down_revision = 'fd6db7be727e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_enterprise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eid', sa.String(length=36), nullable=True),
    sa.Column('reg_no', sa.String(length=255), nullable=True),
    sa.Column('credit_no', sa.String(length=255), nullable=True),
    sa.Column('org_no', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=10), nullable=True),
    sa.Column('econ_kind', sa.String(length=255), nullable=True),
    sa.Column('scope', sa.String(length=255), nullable=True),
    sa.Column('term_start', sa.String(length=255), nullable=True),
    sa.Column('term_end', sa.String(length=255), nullable=True),
    sa.Column('check_date', sa.String(length=255), nullable=True),
    sa.Column('belong_org', sa.String(length=255), nullable=True),
    sa.Column('oper_name', sa.String(length=255), nullable=True),
    sa.Column('oper_type', sa.String(length=255), nullable=True),
    sa.Column('oper_name_id', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.String(length=255), nullable=True),
    sa.Column('end_date', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('type_desc', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('longitude', sa.Float(asdecimal=True), nullable=True),
    sa.Column('latitude', sa.Float(asdecimal=True), nullable=True),
    sa.Column('gd_longitude', sa.Float(asdecimal=True), nullable=True),
    sa.Column('gd_latitude', sa.Float(asdecimal=True), nullable=True),
    sa.Column('obj_id', sa.String(length=50), nullable=True),
    sa.Column('row_update_time', sa.DateTime(), nullable=True),
    sa.Column('province_code', sa.String(length=10), nullable=True),
    sa.Column('district_code', sa.String(length=10), nullable=True),
    sa.Column('title_code', sa.String(length=255), nullable=True),
    sa.Column('econ_kind_code', sa.String(length=255), nullable=True),
    sa.Column('regist_capi_new', sa.String(length=255), nullable=True),
    sa.Column('currency_unit', sa.String(length=10), nullable=True),
    sa.Column('belong_org_code', sa.String(length=255), nullable=True),
    sa.Column('credit_area_code', sa.String(length=255), nullable=True),
    sa.Column('new_status_code', sa.String(length=255), nullable=True),
    sa.Column('type_new', sa.String(length=20), nullable=True),
    sa.Column('category_new', sa.String(length=20), nullable=True),
    sa.Column('out_time', sa.String(length=100), nullable=True),
    sa.Column('diaoxiao_time', sa.String(length=100), nullable=True),
    sa.Column('regist_capi', sa.Float(asdecimal=True), nullable=True),
    sa.Column('created_time', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_enterprise')
    # ### end Alembic commands ###
